language: java
jdk: openjdk11
sudo: required
dist: bionic
services:
 - docker
before_install:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
 - ./dockerbuild.sh
