language: java
jdk: oraclejdk8
sudo: required
dist: xenial
services:
 - docker
before_install:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
 - ./dockerbuild.sh
